### ISSUE TITLE
SUGERENCIA: agregar una nueva sección a tu portfolio.

### ISSUE THREAD

**Issue by cnsvilca** [Niccolello/portfolio-template#1]
# Sección Tecnologías
Hola Nicolas Lello, sugiero agregar una nueva sección a tu portfolio, referida a tecnologías con las que trabajas.
![image](https://user-images.githubusercontent.com/51338806/177427203-590625a3-9d0c-4087-9a34-71eed6741da2.png)
saludos✋

**Comment by Niccolello** [comment]
Me parece correcta espero con ansias la pull request

**Comment by Niccolello** [comment]
Perfecto gracias por tu contribución !
